### ISSUE TITLE
Run `libs/toolkit` in a dev container

### ISSUE THREAD

**Issue by mrodrigues95** [mrodrigues95/spout#29]
With the current container setup, `libs/toolkit` can only be accessed at http://spout.localhost on a local dev setup which interferes with other containers.

```
  toolkit:
    container_name: toolkit
    restart: unless-stopped
    # Explicitly bind 0.0.0.0
    # See: https://github.com/nrwl/nx/issues/2123 
    command: nx run toolkit:storybook --host=0.0.0.0
    build: .
    working_dir: /workspace
    ports:
      - 4400:4400
    volumes:
      - ../:/workspace:rw
    labels:
      - traefik.http.routers.toolkit-http.rule=Host(`spout.localhost`)
      - traefik.http.routers.toolkit-http.service=toolkit
      - traefik.http.services.toolkit.loadbalancer.server.port=4400
```

This is because Storybook automatically redirects and uses query params (e.g. `/?path=/story/button--primary`) in order to access the stories. I've tried using things like `Query('...')` with the current traefik setup but haven't had any success.

Is it worth running Storybook in a dev container or should it only be ran manually when needed?

**Comment by mrodrigues95** [comment]
I managed to get this working with the following config but hot reloading only works within the container when accessing http://localhost:4400/toolkit instead of http://spout.local/toolkit.

```
docker-compose.yml

toolkit:
  container_name: toolkit
  restart: unless-stopped
  # Explicitly bind 0.0.0.0
  # See: https://github.com/nrwl/nx/issues/2123 
  command: nx run toolkit:storybook --host=0.0.0.0 --preview-url=/toolkit/iframe.html
  build: .
  working_dir: /workspace
  ports:
    - 4400:4400
  environment:
    - TOOLKIT_RUNNING_IN_CONTAINER=true
  volumes:
    - ../:/workspace:rw
  labels:
    - traefik.http.routers.toolkit-http.rule=Host(`spout.local`) && PathPrefix(`/toolkit`)
    - traefik.http.routers.toolkit-http.service=toolkit
    - traefik.http.services.toolkit.loadbalancer.server.port=4400
```

```
toolkit/.storybook/main.js

require('dotenv').config();
const rootMain = require('../../../.storybook/main');

const configDevContainer = (config, configType) => {
  // Updates the Storybook public path so that we can use this
  // a little bit better with Traefik.
  // Storybook can be accessed at -> http://spout.local/toolkit when
  // running inside a dev container.
  // See: https://github.com/storybookjs/storybook/issues/1291
  // See: https://github.com/storybookjs/storybook/issues/12270
  if (
    configType === 'DEVELOPMENT' &&
    process.env.TOOLKIT_RUNNING_IN_CONTAINER
  ) {
    config.output.publicPath = '/toolkit';
  }
};

module.exports = {
  ...rootMain,
  stories: [
    ...rootMain.stories,
    '../src/lib/**/*.stories.mdx',
    '../src/lib/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [...rootMain.addons, '@nrwl/react/plugins/storybook'],
  webpackFinal: async (config, { configType }) => {
    // Apply global config.
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType });
    }

    configDevContainer(config, configType);

    return config;
  },
  managerWebpack: async (config, { configType }) => {
    // Apply global config.
    if (rootMain.managerWebpack) {
      config = await rootMain.managerWebpack(config, { configType });
    }

    configDevContainer(config, configType);

    return config;
  }
};

```
